ci: Add deployment check to see if deployed correctly

diff --git a/.github/workflows/moduleSelection-AutoDeployTrigger-40869bd2-733f-4468-93ff-6550eacc47e2.yml b/.github/workflows/moduleSelection-AutoDeployTrigger-40869bd2-733f-4468-93ff-6550eacc47e2.yml
--- a/.github/workflows/moduleSelection-AutoDeployTrigger-40869bd2-733f-4468-93ff-6550eacc47e2.yml
+++ b/.github/workflows/moduleSelection-AutoDeployTrigger-40869bd2-733f-4468-93ff-6550eacc47e2.yml
@@ -42,11 +42,48 @@ jobs:
           containerAppName: moduleselection
           resourceGroup: brady
           imageToBuild: ghcr.io/doc-scientia/moduleselection:${{ github.sha }}
-
-  run-migrations:
+  
+  check-deployment:
     runs-on: ubuntu-latest
     needs: build-and-deploy
     
     steps:
+    - name: Azure Login
+      uses: azure/login@v1
+      with:
+        creds: ${{ secrets.MODULESELECTION_AZURE_CREDENTIALS }}
+    # - name: Wait 1 minute for deployment
+    #   run: sleep 60
+    - name: Validate deployment succeeded
+      run: |
+        while true; do
+            output=$(az containerapp revision list -n moduleselection -g brady --query "[].properties.[healthState,provisioningState]" -o table)
+            if echo "$output" | grep -q None; then
+                sleep 1
+            else
+                break
+            fi
+        done
+
+        if echo "$output" | grep -E "Unhealthy|Failed"; then
+            echo "App failed to deploy"
+            exit 1
+        else
+            echo "App deployed successfully"
+        fi
+
+  run-migrations:
+    runs-on: ubuntu-latest
+    needs: check-deployment
+    
+    steps:
+    - name: Azure Login
+      uses: azure/login@v1
+      with:
+        creds: ${{ secrets.MODULESELECTION_AZURE_CREDENTIALS }}
     - name: alembic upgrade head
-      run: /usr/bin/az containerapp exec --name "moduleselection" --resource-group "brady" --command "alembic upgrade head"
+      run: >
+        /usr/bin/az containerapp exec
+          --name "moduleselection"
+          --resource-group "brady"
+          --command "alembic upgrade head"
